[book]
title = "Finding the Planets"
author = "Daan van Berkel"
description = "A book accompanying a workshop to find the planets around Trappist-1."

[build]
build-dir = "../docs/"

[output.html]
mathjax-support = true